### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum.github.io#16]
As said during the Forum PHP 2015, we should give our users a clear view of how/when we release atoum.

Here are some notes I have on this:
- **strictly stick to semver** (x++ if BC breaks, y++ for any new feature, z++ for any bug-fix)
- 1 release **every 6 weeks** (minor)
- release **ASAP for any bug** (patch)
- every **major is supported for 1 year** after the last minor/patch release
- after 1 year, **we may break BC if required** (and start a new major) wether the last major reached EOL or not
- next major may start before the previous one reaches EOL
- next minor/patch release source code lives on the master branch
## If 2 major releases are living side-by-side
- the oldest will have its own branch and the newest will live on the master branch
- bug-fixes will be backported
- features will be backported if possible
## Extensions (`atoum/*-extension`) / Stubs
- will be released in-sync with atoum to conform to breaking changes (new atoum major release)
- may be released at the same time (minor)
- released ASAP for any bug-fix

@atoum/rms feel free to comment on this, suggest new entry or fix some of them. Once we are OK with those rules, I'll write a blog post.

**Comment by Grummfy** [comment]
:+1:
But for extension we need to do it only for official, I think.
Le 13 janv. 2016 9:03 PM, "Julien BIANCHI" notifications@github.com a
écrit :

**Comment by mikaelrandy** [comment]
Seems good to me, but i need explanations on this point : 

> - after 1 year, **we may break BC if required** (and start a new major) wether the last major reached EOL or not

What is the point ?

**Comment by jubianchi** [comment]
@Grummfy sute this only applies to official extensions (I.E those under the atoum org) ;)

@mikaelrandy Given the rules I wrote, a release EOL date is determined by the last minor/patch release of it. But if at some point (after one year of the major life) we identify that breaking BC somewhere allows us to add new cool features (in atoum itself or through extensions) we start a new major.

Starting a new major will for sure have a side-effect: efforts will be more important on the last major than on the previous so it's worth warning users that after one year of life we may start a new major and ship less new things on the previous one.

**Comment by jubianchi** [comment]
I'm wondering if we should add a rule saying that we limit living major versions to a maximum of 2. Once we have to start a third one, the oldest will die.

**Comment by Hywan** [comment]
@jubianchi We can add such a rule yes. It might not happen but who knows :-).
I would not say anything about extensions however. We can't make such hard assumption on the whole atoum's ecosystem. This is hard to maintain and keep.

**Comment by mikaelrandy** [comment]
@jubianchi +1 on the rule about limiting numbers of living major version

**Comment by jubianchi** [comment]
We should add a note on deprecations:
- Features **may** be marked as deprecated at any time in any minor version: this should at worst display a notice but the feature should be kept fully-functional. The notice **must** contain hints on the alternatives.
- Once we start the new major branch deprecated feature will be removed

**Comment by mikaelrandy** [comment]
:+1:

**Comment by Grummfy** [comment]
I have started to work on this #68
