### ISSUE TITLE
Add GrumPHP in the third-party integrations

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum.github.io#50]
We should add phpro/grumphp to third-party integrations.

We should get in touch with the authors (@veewee, @aderuwe) to see if we can use their logo on our website.

Here are some useful links:
- project: https://github.com/phpro/grumphp
- documentation: https://github.com/phpro/grumphp/blob/master/doc/tasks/atoum.md
- twitter: https://twitter.com/GrumPhp

**Comment by veewee** [comment]
Sounds great! Feel free to use the GrumPHP logo on your website.

**Comment by jubianchi** [comment]
@veewee thanks!
