### ISSUE TITLE
Default to opened menu

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum.github.io#6]
When the users lands on the website, the menu should be opened by default

**Comment by mikaelrandy** [comment]
For me, the menu animation is useless. And even maybe dangerous.

People who come on atoum website don't come for a whole navigation, but for a specific purpose, and want to find easily, fastly and directly the page who answers their question.
And a closed menu which need to understand there is a button to open it is not a good idea.

That was the reason why i had put a fixed menu.

**Comment by jubianchi** [comment]
@mikaelrandy closing the menu can be useful on small screens this is why I restored the animation and close button.

**Comment by Hywan** [comment]
We can close the menu on small screens and keep it open on big screen. With a `@media` query, this is very easy to do. Thoughts?

**Comment by jubianchi** [comment]
@Hywan :+1: but on large screen I think we should still default to an opened menu

**Comment by Grummfy** [comment]
menu closed make people not necessarly discover it. So Now, when you come to the home apge you are lost ...

using "standard" icon for menu like the tripple burger icon could partially solve the problem.

Love the idea from Hywan too (keep menu open for big screen)

**Comment by Hywan** [comment]
@jubianchi And keep it open, yes. It's easy to remove the “menu” icon too, simply `display: none` and done.

**Comment by Hywan** [comment]
Also, the menu on hoa-project.net is always closed by default, and it's not a problem. From our analytics, people explore the website easily.

**Comment by mikaelrandy** [comment]
I like the idea to let the menu open on big resolution, and display the "open menu" button on lower resolution :+1:

**Comment by Grummfy** [comment]
@Hywan icon of hoa is the triple burger icon, the "standard" menu icon.

**Comment by Hywan** [comment]
@Grummfy But a burger does not roll ;-).

**Comment by mikaelrandy** [comment]
:dancer:
