### ISSUE TITLE
Update of Phar file failes. Connection refused by server.

### ISSUE THREAD

**Issue by estebanthebad** [atoum/atoum.github.io#77]
https://atoum.readthedocs.io/en/latest/installation.html#update

The update code listed there does not work.
```
$ php -d phar.readonly=0 atoum.phar --update
Checking if a new version is available...
Error: file_get_contents(http://downloads.atoum.org/update.php?version=["2.5.0"]): failed to open stream: Connection refused by server.
```

**Comment by Grummfy** [comment]
Sh**t I was thinking we have removed the phar install... I will update the documentation becuase for the moment, the phar build is broken, and we didn't plan to fix it yet
